### ISSUE TITLE
Master Filter should exclude items tagged 'infuse'

### ISSUE THREAD

**Issue by bradchoate** [TMMania/TMManias-DIM-Filter-Gallery#1]
I don't want to accidentally delete items specifically tagged for infusion. Doesn't always mean max PL, since not everyone is getting max PL gear.

Also, for some reason, items at 1260 are not being excluded by the `-is:maxpower` term I see in the query.

**Comment by TMMania** [comment]
Yep tag infusion is something I definitely overlooked, added.

Also unfortunately with the way that DIM works, it only identifies one item that is at your maxpower and will not identify all items at max power and I'll slot in a "-power:>=1260" which can result in a build up of 1260s, but I feel like people would rather have it than not.

From Ace (DIM Contributor): "maxpower is not a search for maxpowered items. its a search for YOUR maxpowered loadout."
