### ISSUE TITLE
Items with tag:archive are not being excluded from Master Filter

### ISSUE THREAD

**Issue by trevorstinson** [TMMania/TMManias-DIM-Filter-Gallery#6]
The Master Filter is matching against items with the Archive tag, despite the presence of `-(is:tagged -tag:junk)` in the filter rules.

Other tags (keep, favorite, infuse) are correctly excluded.

**Comment by trevorstinson** [comment]
I looked at the recent filter changes and played around with my vault a little bit, and I found that this only affects common and uncommon items. The issue is actually that the filter matches common and uncommon items regardless of whether they have tags. Use case: I have a few of the early Red War items archived for sentimental reasons.

**Comment by delphiactual** [comment]
The likely culprit is that `-tag:archive` is included in the default search, so this search must be doing something to modify that

**Comment by TMMania** [comment]
Ah yes, I just recently put in a "we're keeping nothing that is common or uncommon" statement and I put it at the end to make that an "all powerful" rule, I'll change it to be affected by tags, sorry about that.

**Comment by TMMania** [comment]
Issue is now fixed.

**Comment by trevorstinson** [comment]
Awesome, thank you.
