### ISSUE TITLE
new NthHighest: condition less results

### ISSUE THREAD

**Issue by mistral13** [TMMania/TMManias-DIM-Filter-Gallery#8]
Hi.

thank you for this nice tool. :-)

with the new filter condition (NthHighest) fewer items are found for me (new 46; old 60).
For example, the following items are no longer found:

![image](https://user-images.githubusercontent.com/5049663/121160883-c437e800-c84c-11eb-98ad-6815afb03277.png)

![image](https://user-images.githubusercontent.com/5049663/121161045-e5003d80-c84c-11eb-8479-cb25585bd3a1.png)

![image](https://user-images.githubusercontent.com/5049663/121161148-fea18500-c84c-11eb-8185-91eddbf5be40.png)

![image](https://user-images.githubusercontent.com/5049663/121161279-20027100-c84d-11eb-8f13-3d561ad11b6a.png)

![image](https://user-images.githubusercontent.com/5049663/121161344-2f81ba00-c84d-11eb-9f83-e38103a44715.png)

![image](https://user-images.githubusercontent.com/5049663/121161454-4a542e80-c84d-11eb-9d6a-08d752a7af87.png)

is that correct or is new filter a mistake?

**Comment by TMMania** [comment]
These are correct, but the condition will be more strict soon.

I'm currently doing an analysis of every single possible armor roll and categorizing and summarizing that data and added a few conditions recently that will identify more armor than necessary to make sure that when that analysis is done that nothing that _could_ have been kept was deleted when I refine those conditions. So for now, there will be less results, but I'll be fine tuning the armor filtering once that analysis is done.
